source = $HOME/.config/hypr/modules/mocha.conf

$accent = $mauve
$accentAlpha = $mauveAlpha
$font = CodeNewRoman Nerd Font

general {
  immediate_render = false
  disable_loading_bar = true
  fail_timeout = 1500
  hide_cursor = false
}

background {
  path = screenshot
  blur_passes = 2
  blur_size = 3
  brightness = 0.6
}

# TIME
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%R")"
  color = $text
  font_size = 80
  font_family = $font
  position = 20%, -155
  halign = left
  valign = top
}

# DATE 
label {
  monitor = 
  text = cmd[update:43200000] echo "<b>$(date +"%d %B %Y")</b>"
  color = $text
  font_size = 20
  font_family = $font
  position = 24%, -265
  halign = left
  valign = top
}

# 2nd background
shape {
  monitor = 
  size = 36%, 100%
  color = $base
  halign = right
  valign = center

  shadow_passes = 3
  shadow_size = 15
  shadow_color = $crust
  shadow_boost = 1.2
}

# USER AVATAR
image {
  monitor = 
  path = ~/.face.jpg
  size = 250
  border_color = $accent
  border_size = 3

  position = -8%, 110
  halign = right
  valign = center
  zindex = 2
}

# USER NAME
label {
  monitor = 
  text =$USER
  color = $text
  font_size = 28
  font_family = $font
  position = -15%, -95
  halign = right
  valign = center
  zindex = 2
}

# INPUT FIELD
input-field {
  monitor =
  rounding = 25
  size = 250, 8%
  outline_thickness = 3
  dots_size = 0.24
  dots_spacing = 0.24
  dots_center = true
  outer_color = $accent
  inner_color = $surface0
  font_color = $text
  fade_on_empty = false
  placeholder_text = 
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>failure.</i>
  capslock_color = $yellow
  position = -8%, -175
  halign = right
  valign = center
  zindex = 2
}
